#!/bin/bash

# GNU General Public License v3.0
# This script is licensed under the GNU GPL v3.0. See LICENSE file for details.

select server in $(sed -n "s/^Host \(.*\)/\1/p" ~/.ssh/config) ; do [[ $server ]] && ssh $server ; break ; done

